name: Deploy Static Site

on:
  push:
    branches:
      - master  # 触发条件为 master 分支上的推送

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main  # 切换到 main 分支

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Cache node modules
      uses: actions/cache@v4
      id: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Create orphan branch for deployment (if necessary)
      run: |
        if ! git show-ref --quiet refs/remotes/origin/main; then
          git checkout --orphan main
          git rm -rf .
          echo "Initial commit" > README.md
          git add README.md
          git commit -m "Initial commit on main branch"
          git push origin main
        fi

    - name: Copy build output to main branch
      run: |
        git checkout main
        cp -r dist/* ./
        git add .
        git commit -m "Deploy to GitHub Pages [skip ci]" || echo "No changes to commit"
        git push origin main